[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: increase function timeout if needed
[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["nodemailer"]
  timeout = 15


